name: Deploy MkDocs Site to GitHub Pages

on:
  push:
    branches:
      - mkdocs_server  # Trigger deployment on changes to the main branch
  workflow_dispatch:  # Allow manual deployment trigger

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check Out Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set Up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Step 3: Install MkDocs and Material Theme
      - name: Install Dependencies
        run: |
          pip install mkdocs mkdocs-material

      # Step 4: Deploy to GitHub Pages
      - name: Deploy MkDocs Site
        run: mkdocs gh-deploy --force
