name: Deploy MkDocs Site to GitHub Pages

on:
  push:
    paths:
      - "docs/**"
    branches:
      - main  
  workflow_dispatch:  # Allow manual deployment trigger

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check Out Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set Up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Step 3: Install MkDocs and Dependencies
      - name: Install Dependencies
        run: |
          pip install mkdocs mkdocs-material pyyaml

      # Step 4: Generate Navigation
      - name: Generate Navigation
        run: python generate_nav.py

      # Step 5: Commit Updated mkdocs.yml
      - name: Commit Updated mkdocs.yml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add mkdocs.yml
          git commit -m "Update mkdocs.yml with dynamic navigation" || echo "No changes to commit"
          git push origin main

      # Step 6: Deploy to GitHub Pages
      - name: Deploy MkDocs Site
        run: mkdocs gh-deploy --force
